junit_tests(name = 'normalizer',
  dependencies = [
    pants('3rdparty:junit'),
    pants('3rdparty:scalatest'),
    pants('3rdparty:thrift'),
    pants('src/scala/com/twitter/penguin/korean/normalizer'),
  ],
  sources = globs('*.scala')
)
